spring:
  liquibase:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    test-connection: false
    username: ${gmail.username:juliuskrah@example.com}
    password: ${gmail.password:123456789}
    properties:
      mail.smtp.starttls.enable: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.HSQLDBDelegate
com:
  juliuskrah:
    quartz:
      async:
        core-pool-size: 5
        max-pool-size: 6
        queue-capacity: 100
logging:
  level:
    com.juliuskrah.quartz: debug
    
  