liquibase:
  enabled: true
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: localhost
    port: 25
    test-connection: false
    username: ${gmail.username:admin}
    password: ${gmail.password:admin}
    properties:
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
com:
  juliuskrah:
    quartz:
      config-location: classpath:quartz.properties
logging:
  level:
    com.juliuskrah.quartz: debug

# Running with Java 9
# > mvnw clean package -DskipTests
# > java --add-modules java.xml.bind --illegal-access=warn -jar target\quartz-manager.jar
    
  