spring:
  datasource:
    url: jdbc:postgresql:quartz
    hikari:
      username: postgres
      password: root
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    

    
  