spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    test-connection: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.HSQLDBDelegate
com:
  juliuskrah:
    quartz:
      async:
        core-pool-size: 5
        max-pool-size: 6
        queue-capacity: 100
logging:
  level:
    com.juliuskrah.quartz: debug

# Running with Java 9
# > mvnw clean package -DskipTests
# > java --add-modules java.xml.bind --illegal-access=warn -jar target\quartz-manager.jar
    
  